### ISSUE TITLE
Meeting ended in error: Meeting has ended

### ISSUE THREAD

**Issue by a-creation** [VapiAI/web#1]
Call randomly disconnects and just throws an error: "Meeting ended in error: Meeting has ended" 

Any reason why this might be? 

Just using default imports

**Comment by jordancde** [comment]
Hey @a-creation ! Sorry for the delay, can you ensure that a credit card is added to your account in the Vapi dashboard? 

Will be adding better error handling here soon.

**Comment by yuppiesupper111** [comment]
I added my card to my account and it's still getting the error meeting has ended when testing a workflow.
