### ISSUE TITLE
How to setup silenceTimeoutSeconds in Web client?

### ISSUE THREAD

**Issue by boveylisi2013** [VapiAI/web#10]
How to setup silenceTimeoutSeconds in Web client?
I could find it in https://docs.vapi.ai/api-reference/calls/create-web-call
But not available here.

**Comment by nikhilro** [comment]
`assistant.silenceTimeoutSeconds` doesn't work? 

```
vapi.start({ ...other stuff, silenceTimeoutSeconds: X})
```

**Comment by boveylisi2013** [comment]
It worked! Thanks!
