### ISSUE TITLE
Webkit/Tauri Support?

### ISSUE THREAD

**Issue by GoldinGuy** [VapiAI/web#15]
Hi! Was looking into using VapiAI in Tauri but I get the following error when trying to run the application:

```
error: unsupported browser: UnsupportedError: device not supported
Meeting ended in error: Your browser is not supported for this call
Ignoring settings for browser- or platform-unsupported input processor(s): audio
call has stopped
```
I believe this is because webkit may not be supported?

**Comment by nikhilro** [comment]
(resolved over email, feel free to reopen if not. for posterity:)

Yes, there might be some limitation where Tauri doesn't support the full WebRTC stack. It's easiest to use Electron for now. It's on the list to investigate but likely not anytime soon.
