### ISSUE TITLE
How can I set the volume of the Voice Assistant

### ISSUE THREAD

**Issue by seflless** [VapiAI/web#16]
We're receiving volume levels, but the voice assistant doesn't get quieter. Am I responsible for calling some API to apply it? I'm assuming this would get me ducking the audio when I talk over the assistant?

Related, how can I make it interrupt the agent when I talk, it doesn't seem to be doing that by default.

**Comment by nikhilro** [comment]
(resolved in huddle, commenting for posterity):

there's some undocumented functionality in the SDK:

To toggle the user:
```
vapi.setMuted()
```

To toggle the assistant:
```
vapi.send({ type: 'control', control: 'mute-assistant'})
vapi.send({ type: 'control', control: 'unmute-assistant'})
```

Using these primitives, it's possible to construct any interruption or push-to-talk interface

**Comment by jingwei99** [comment]
👋 

It seems `mute-assistant` stops the conversation right now/today (not sure when did it start), my guess is this is a regression, could you look into it? 

+ @phanquanghung (who actually found out about this 🙏)
