### ISSUE TITLE
getting an error when initialising a new Vapi

### ISSUE THREAD

**Issue by werneroi** [VapiAI/web#17]
when doing a simple step 1:
import Vapi from '@vapi-ai/web';
const vapi = new Vapi('token here');

I am getting the error: 
TypeError: Vapi is not a constructor

hard to believe i am doing something wrong in these line... can someone help?

**Comment by nikhilro** [comment]
hey @werneroi sorry about the delay. i think you're not using the SDK in a browser environment. maybe try one of our examples: https://github.com/VapiAI/client-side-example-javascript-react
