### ISSUE TITLE
Even after connecting sometimes it doesn't responds after the firstMessage

### ISSUE THREAD

**Issue by mayank-holofy** [VapiAI/web#19]
```
To Init 
vapiRef.current = new Vapi('api-token');
vapiRef.current.on('message', (message) => {
});

vapiRef.current.on('speech-start', () => {
console.log('Speech has started');
});

vapiRef.current.on('speech-end', () => {
console.log('Speech has ended');
});

vapiRef.current.on('call-start', () => {
console.log('Call has started');
});

vapiRef.current.on('call-end', () => {
console.log('Call has stopped');
});

To Start 
  vapiRef.current.start({
  model: {
    provider: 'openai',
    model: 'gpt-3.5-turbo',
    messages: [
      {
        role: 'system',
        content: vapiSystemPromptRef.current,
      },
    ],
  },
  voice: {
    provider: 'azure',
    voiceId: 'en-US-AvaNeural',
  },
  firstMessage: 'Hey!',
  responseDelaySeconds: 0.7,
});
```

After the first Message it says hi it stops

**Comment by nikhilro** [comment]
* Any errors in the network tab? 
* Check the call logs in the dashboard?

**Comment by mayank-holofy** [comment]
Didn't checked the logs
`
caught TypeError: Cannot read properties of undefined (reading 'producers')
    at e.value (eval at <anonymous> (daily-esm.js:7:83831), <anonymous>:9:532100)
    at eval (eval at <anonymous> (daily-esm.js:7:83831), <anonymous>:9:531689)

`

**Comment by sagar-vapi** [comment]
can you provide a callIId which has the error ? Will be easier for us to see whats going on

**Comment by mayank-holofy** [comment]
> can you provide a callIId which has the error ? Will be easier for us to see whats going on

71de7643-3d1d-4dd1-afe6-612e74037f02
Is the call id @sagar-vapi

**Comment by nikhilro** [comment]
From what I can tell, no audio came through from your side or at least call was ended from the frontend before anything came through on that callId. 

Could you email support@vapi.ai with some more recent call IDs if still an issue. That's the best channel for integration debugging. This is best for SDK bugs.

**Comment by sgouseshaik** [comment]
Dear Vapi Support Team,

I am experiencing an issue while trying to create a new assistant on the Vapi Dashboard. After logging in to https://dashboard.vapi.ai/ and attempting to create a new assistant, the screen does not move forward, preventing me from completing the process.

Could you please look into this issue and provide guidance on how to resolve it? If any additional details are required, please let me know.

Looking forward to your prompt support.
![Image](https://github.com/user-attachments/assets/215147f6-235e-4e57-bb6f-3fe6a027f44e)


Regards,
Ghous.
