### ISSUE TITLE
Security concerns

### ISSUE THREAD

**Issue by Harsh4999** [VapiAI/web#2]
So we just tried implementing it in a next.js application and it is working but our only concern is it is required for us to expose the API key in frontend which is not a secure method and our api key would be hanging in frontend. I am also not able to find a way to implement this in a backend server or some other service and extend that to frontend that way it would be more secure. Do let us know how to make this secure. Currently we are using env vars but that too leaks the key in browser.

Code:
```
    
    const vapi = new Vapi(process.env.NEXT_PUBLIC_VAPI_KEY??"");
    const start =  ()=>{
        vapi.start(process.env.NEXT_PUBLIC_VAPI_ASSISTANT_ID??"")
        
    }
    useEffect(()=>{
        start()
        vapi.on('speech-start', () => {
            console.log('Speech has started');
          });
          
        vapi.on('speech-end', () => {
            console.log('Speech has ended');
        });
        
        vapi.on('call-start', () => {
            console.log('Call has started');
        });
        
        vapi.on('call-end', () => {
            console.log('Call has stopped');
        });
        
        vapi.on('volume-level', (volume) => {
            console.log(`Assistant volume level: ${volume}`);
        });
        
        vapi.on('error', (e) => {
            console.error('ASSISTANT ERROR',e)
        });
        
        return ()=>{
            vapi.stop()
        }
    },[])
```
Do suggest most secure method

**Comment by nikhilro** [comment]
Public key is separate from API key. Feel free to email me at nikhil@vapi.ai if confusing
