### ISSUE TITLE
Local audio/microphone events

### ISSUE THREAD

**Issue by tripproberts** [VapiAI/web#20]
Is it possible to expose events related to the local audio/microphone similar to `speech-start` and `speech-end` for assistant audio? On quick glance, daily-js seems to publish `DAILY_EVENT_LOCAL_AUDIO_LEVEL` [events](https://github.com/daily-co/daily-js/blob/581eb3b4e0b05abee452292a30a03336c5072fce/src/module.js#L4721C12-L4721C41)

**Comment by nikhilro** [comment]
It's not documented well.

1. Set `clientMessages` on the assistant: https://docs.vapi.ai/api-reference/assistants/create-assistant
<img width="714" alt="image" src="https://github.com/VapiAI/web/assets/22201788/fa9f74f0-0f4a-4a4b-9049-5be5b19ddc52">

2. listen to vapi.on("message")

3. "speech-update" is what you're looking for.

currently there is no place where we document what "speech-update" message actually looks like and what it's contents for now. we should do that. for now, just enable all the messages and print it out to get a feel for the system
