### ISSUE TITLE
Increase seconds for responseDelaySeconds

### ISSUE THREAD

**Issue by wheel1992** [VapiAI/web#25]
Hi Vapi team,

My product aims to improve student's communication skills in Singapore by providing real life conversation topics. 

Our primary audiences are students who are weak in conversation and tend to stuck at replying.

Therefore, we have tried to increase `responseDelaySeconds` to 2 seconds but it is not enough.

I proposed to increase to a maximum of `10` seconds to ensure people have enough time to response to the AI.

**Comment by wheel1992** [comment]
Hi @nikhilro 

May I check if this is feasible to increase from `2s` to `10s` or even X seconds, maximum of 1 minute.

**Comment by nikhilro** [comment]
We increased the maximum to 5. Could you try if that works better? 10 would be a lot. It's live on staging-api.vapi.ai

**Comment by wheel1992** [comment]
> We increased the maximum to 5. Could you try if that works better? 10 would be a lot. It's live on staging-api.vapi.ai

Hi @nikhilro ,
Thank you for the increase. May I check how do we connect to staging api?

**Comment by wheel1992** [comment]
Hi @nikhilro 

Apology for clarifying, how do we connect to staging using the `staging-api.vapi.ai` through the web sdk?

**Comment by nikhilro** [comment]
It's live on api.vapi.ai now
