### ISSUE TITLE
Add OpenAI model - gpt-4o

### ISSUE THREAD

**Issue by wheel1992** [VapiAI/web#31]
Hi @nikhilro 

We would like to add support for OpenAI's `gpt-4o` model.

**Comment by nikhilro** [comment]
If the types in Web SDK go out of date, you can use `as any`. It'll work correctly because API supports it.

**Comment by remyma** [comment]
Yes @nikhilro, it works as a workaround, but it's not ideal, especially when working in typescript script mode. I would rather leave this issue opened and close it when types are up2date, I was about to open a new issue on the topic before I noticed this one was closed.

**Comment by nikhilro** [comment]
Totally fair. Feel free to make a PR. We just use `npm run generate-api` which pulls from the OpenAPI spec at api.vapi.ai/api. At some point, we'll have a better automated system for all of this.

**Comment by remyma** [comment]
@sahilsuman933 already merged a MR for that recently, but I think you need to generate a new release so we can upgrade the dependency on our side

**Comment by nikhilro** [comment]
good point done
