### ISSUE TITLE
Call automatically deleted right after it initialised

### ISSUE THREAD

**Issue by wheel1992** [VapiAI/web#39]
As title mentioned, the call just deleted after the call is initialised.

Package version
```
"@vapi-ai/web": "1.1.6"
```

<img width="877" alt="image" src="https://github.com/VapiAI/web/assets/10736160/1509cd4c-f97a-4c07-bf5a-6c4b8427daf0">

**Comment by wheel1992** [comment]
@nikhilro

**Comment by nikhilro** [comment]
check the call logs on dashboard.vapi.ai why the call failed

**Comment by wheel1992** [comment]
@nikhilro 

That's really helpful! Manage to solve the problem by checking the logs from dashboard call logs
