### ISSUE TITLE
Analysis plan

### ISSUE THREAD

**Issue by remyma** [VapiAI/web#40]
Hello, 

Last release npm version is `1.1.7`, it does not contains analysis plan. Can you release a new version to include it ? (I see analysis plan is already on the main branch)

Thanks

**Comment by nikhilro** [comment]
That's odd, latest is 1.4.0: https://www.npmjs.com/package/@vapi-ai/web

Where are you seeing 1.1.7?

**Comment by remyma** [comment]
I could use it in my package.json: 

![Screenshot from 2024-06-11 22-04-15](https://github.com/VapiAI/web/assets/2292735/b5f4f353-9986-4fe9-91a1-691375f35c75)


```
  /@vapi-ai/web@1.1.7:
    resolution: {integrity: sha512-fP9S6uVPLCr0lvK+18DBQYDCTcQFUxm79fZ785sh8FfQRT3j2iFgQJILf38I476OWXDcC+heWmTKaGvuseiI4A==}
    dependencies:
      '@daily-co/daily-js': 0.58.0
      events: 3.3.0
    dev: false
    ```

**Comment by remyma** [comment]
sorry, I messed up with the numbers :rofl: , last one is indeed 1.4.0

**Comment by remyma** [comment]
My bad, I close the issue.
