### ISSUE TITLE
issue with 1.4.0 types: clientMessages and serverMessages

### ISSUE THREAD

**Issue by remyma** [VapiAI/web#41]
Seems that clientMessages and serverMessages are not array anymore? 

```
/**
   * These are the messages that will be sent to the Client SDKs. Default is ['transcript', 'hang', 'tool-calls', 'speech-update', 'metadata', 'conversation-update']
   * @example ["transcript","hang","tool-calls","speech-update","metadata","conversation-update"]
   */
  clientMessages?:
    | 'status-update'
    | 'speech-update'
    | 'transcript'
    | 'hang'
    | 'function-call'
    | 'tool-calls'
    | 'metadata'
    | 'conversation-update'
    | 'model-output'
    | 'voice-input';
```

```
serverMessages?:
    | 'status-update'
    | 'transcript'
    | 'hang'
    | 'function-call'
    | 'tool-calls'
    | 'end-of-call-report'
    | 'conversation-update'
    | 'phone-call-control'
    | 'model-output'
    | 'voice-input';
```

**Comment by nikhilro** [comment]
limitation of OpenAPI to Typescript types tool we use `swagger-typescript-api`. Here's our OpenAPI: https://api.vapi.ai/api-json. If you find a better tool, we can use that. Otherwise, just use `as any` for now

**Comment by remyma** [comment]
But these types were ok 2 weeks ago, and you used the same tool, right? why does it changed?

**Comment by remyma** [comment]
Don't know why I hadn't this error before...
But yes, I found an opened issue on the library about this (if it's the correct lib?): https://github.com/acacode/swagger-typescript-api/issues/524

I'll escape these errors with `// @ts-expect-error` for now

**Comment by nikhilro** [comment]
We manually fixed it last time but not sustainable :(

**Comment by tripproberts** [comment]
So your decision is to ship a broken typescript api? Weird...

**Comment by nikhilro** [comment]
Ya that's fair criticism. I'll try to look for a better package. Just bug with other feature work and this is an easy fix of `as any` on that specific field. Most people use `assistantId` anyways.

**Comment by tripproberts** [comment]
Fair! Just not great when things break unexpectedly without a major version bump
