### ISSUE TITLE
Property 'forwardingPhoneNumbers' does not exist on type 'Assistant'

### ISSUE THREAD

**Issue by remyma** [VapiAI/web#42]
Seems there is a breaking change since I updated to last version: "@vapi-ai/web": "^1.4.0",

there is no 'forwardingPhoneNumbers' property anymore on type 'Assistant'

**Comment by nikhilro** [comment]
Deprecated, use Transfer Call Tool

**Comment by nikhilro** [comment]
(The old way is still supported but just hidden in schema)

**Comment by remyma** [comment]
got it, thanks @nikhilro

**Comment by remyma** [comment]
Is it documented somewhere? documentation still describes the deprecated process: https://docs.vapi.ai/call-forwarding
