### ISSUE TITLE
Incorrect type for clientMessages and serverMessages

### ISSUE THREAD

**Issue by rbasto1** [VapiAI/web#44]
Since version 1.2.0 the types for `CreateAssistantDTO.clientMessages` and `CreateAssistantDTO.serverMessages` are incorrect. Instead of an array of a string enum it is declared as just a string enum. Last version where it was correct was 1.1.7. The corresponding code is at `web/api.ts` lines 1871 to 1896 (generated by Swagger).

**Comment by nikhilro** [comment]
Unfortunate fact of the generator we're using. If you know a better one, please let me know!

Discussion: https://github.com/VapiAI/web/issues/41
