### ISSUE TITLE
Assistant.clientMessages and serverMessages type issue

### ISSUE THREAD

**Issue by tripproberts** [VapiAI/web#48]
Why were assistant `clientMessages` and `serverMessages` updated to only allow a single message type instead of an array? 

https://github.com/VapiAI/web/pull/33/files#diff-216c63c6346d7d78fcd3b1ceeae8c9772b30f8fb2d43b8beabcda6ebd6aa6660L1267

**Comment by nikhilro** [comment]
Unfortunate fact of the generator we're using. If you know a better one, please let us know!

Discussion: https://github.com/VapiAI/web/issues/41
