### ISSUE TITLE
Vapi's AI isn't accurate when asked today's date.

### ISSUE THREAD

**Issue by Rudresh-sisode** [VapiAI/web#49]
https://auth.vapi.ai/storage/v1/object/public/recordings/ab33bb2c-e94c-4df0-ac74-a82c46970e95-1719991630375-23e30f3c-799a-4bb2-b5ad-2dc41e07ec37-mono.wav

please go through the web-call's log.
this call log is made on 3 July 2024 at 12:56 PM (IST)
When I asked, "what is the date of today?"
it's responding me 6 October 2023? why is that so.
And even when I asked the same question to Vapi's AI test on Vapi's home page,
in respond I get September 2023

**Comment by sahilsuman933** [comment]
It is because LLM models aren't aware of today's date that you will need to provide the current time.

Check any of the video from here to get the information about it https://docs.vapi.ai/community/appointment-scheduling

**Comment by Rudresh-sisode** [comment]
Ok, considering your point too, that LLM isn't aware about today's or tomorrow's date.
but **why it responding me wrong date**, it would simply says to me that "Not aware about it", as other LLM answers.
If Vapi isn't aware about the information it **should not hallucinate the answer.** That's the next job need to be done.

**Comment by sahilsuman933** [comment]
You should consider reading this discussion https://community.openai.com/t/how-do-we-make-llm-understand-the-context-of-time/328978/5

@Rudresh-sisode
