### ISSUE TITLE
Krisp filter init error

### ISSUE THREAD

**Issue by chen-rn** [VapiAI/web#6]
I have a super simple NextJS frontend that looks like this

```
"use client";
import { vapi } from "@/utils/vapi";

export default function Home() {
  const startVapi = () => {
    vapi.on("error", (e) => {
      console.error(e);
    });

    vapi.start({
      model: {
        provider: "openai",
        model: "gpt-3.5-turbo",
        systemPrompt: "You're an assistant...",
      },
      voice: {
        provider: "11labs",
        voiceId: "burt",
      },
    });
  };

  return (
    <div className="flex min-h-screen flex-col items-center justify-between">
      <button onClick={startVapi}>Start Vapi</button>
    </div>
  );
}

```

When I click the button, it asks for microphone permissio, and then after a second or so shows a Krisp filter error.

![Screenshot 2024-01-22 at 7 38 45 PM](https://github.com/VapiAI/web/assets/36214945/eba5f146-88e5-48aa-9a3c-f6a9a3c17e69)

**Comment by chen-rn** [comment]
Update: Seems like the issue may be related to my Chrome. Switched to Safari and everything seems to be working properly.

**Comment by chen-rn** [comment]
Seems like this happens on Arc as well... Honestly not too sure how to get it to work with my main browsers.

**Comment by nikhilro** [comment]
We're still investigating but current best guess is some chrome extension preventing Krisp WASM from loading. Would you mind trying it in incognito with all extensions disabled for me?

**Comment by chen-rn** [comment]
I tried that and it doesn't seem to be related to extensions.(also tried to reset chrome)

The only thing related to Krisp that I can think of is that in the past I've installed their app. But uninstalled shortly after.

**Comment by nikhilro** [comment]
Could you email me your browser information and a callId where this happens? nikhil@vapi.ai

**Comment by nikhilro** [comment]
Resolved in Slack
